#ifndef SCRAPBRAIN_MIDICC_H
#define SCRAPBRAIN_MIDICC_H 1

// TODO: PM Start
enum MidiController {
    LFORate_MidiController = 3,
    Algorithm_MidiController = 9,
    AMDepth_MidiController = 14,
    PMDepth_MidiController = 15,
    Op1_AMStart_MidiController = 16,
    Op2_AMStart_MidiController = 17,
    Op3_AMStart_MidiController = 18,
    Op4_AMStart_MidiController = 19,
    Op1_Level_MidiController = 20,
    Op2_Level_MidiController = 21,
    Op3_Level_MidiController = 22,
    Op4_Level_MidiController = 23,
    Op1_Velocity_MidiController = 24,
    Op2_Velocity_MidiController = 25,
    Op3_Velocity_MidiController = 26,
    Op4_Velocity_MidiController = 27,
    Op1_Start_MidiController = 28,
    Op2_Start_MidiController = 29,
    Op3_Start_MidiController = 30,
    Op4_Start_MidiController = 31,
    Op1_FreqX_MidiController = 70,
    Op2_FreqX_MidiController = 71,
    Op3_FreqX_MidiController = 72,
    Op4_FreqX_MidiController = 73,
    Op1_Detune_MidiController = 74,
    Op2_Detune_MidiController = 75,
    Op3_Detune_MidiController = 76,
    Op4_Detune_MidiController = 77,
    Op1_Feedback_MidiController = 78,
    PMStart_MidiController = 79,
    Op1_Attack_MidiController = 85,
    Op1_Decay1_MidiController = 86,
    Op1_Sustain_MidiController = 87,
    Op1_Decay2_MidiController = 88,
    Op1_Release_MidiController = 89,
    Op1_EnvScale_MidiController = 90,
    Op2_Attack_MidiController = 102,
    Op2_Decay1_MidiController = 103,
    Op2_Sustain_MidiController = 104,
    Op2_Decay2_MidiController = 105,
    Op2_Release_MidiController = 106,
    Op2_EnvScale_MidiController = 107,
    Op3_Attack_MidiController = 108,
    Op3_Decay1_MidiController = 109,
    Op3_Sustain_MidiController = 110,
    Op3_Decay2_MidiController = 111,
    Op3_Release_MidiController = 112,
    Op3_EnvScale_MidiController = 113,
    Op4_Attack_MidiController = 114,
    Op4_Decay1_MidiController = 115,
    Op4_Sustain_MidiController = 116,
    Op4_Decay2_MidiController = 117,
    Op4_Release_MidiController = 118,
    Op4_EnvScale_MidiController = 119
};

#endif
